name: practica_final_4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0
  mobile_scanner: ^6.0.3
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqflite: ^2.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
